#!/bin/bash

cd /var/www/soisy/webapp/scripts/

if [[ $1 == *SpecShop.js ]]; then
    ./node_modules/protractor/bin/protractor protractor-conf-shop.js --specs /var/www/soisy/docs/specs/$1
else
    ./node_modules/protractor/bin/protractor protractor-conf.js --specs /var/www/soisy/docs/specs/$1
fi
